#!/bin/bash

# I prefer that to be a directory
mkdir -p $HOME/.config

alldots=(            \
  $HOME/.bashrc      \
  $HOME/.Xresourcas  \
  $HOME/.Xdefaults   \
  $HOME/.tmux.conf   \
  $HOME/.gitconfig   \
  $HOME/.config/nvim \
  $HOME/.tmux        \
)

# Clean old config files and directories
for p in "${alldots[@]}"
do
  rm -rfv $p
done

for f in bash tmux nvim urxvt git docker
do
  stow -D $f
  stow $f
done
